image: docker

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  # Install node and some other deps
  - sudo curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - sudo apt-get update -yq
  - sudo apt-get install -y apt-transport-https build-essential cmake nodejs python-software-properties software-properties-common unzip
  
  # Install yarn
  - sudo wget -q -O - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - sudo echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -yq
  - sudo apt-get install -y yarn

install_dependencies:
  stage: build
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/

unit_e2e_test:
  stage: test
  script: yarn test

deploy:
  stage: deploy
  script:
    - docker build . -t portfolio
    - docker run -d -p 8080:80 portfolio
  when: manual