image: node:latest

stages:
  - build
  - test
  
before_script:
  - wget -q -O — https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
  - echo ‘deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main’ | tee /etc/apt/sources.list.d/google-chrome.list
  - apt-get update
  - apt-get install google-chrome-stable -y
  - yarn config set cache-folder .yarn
  - yarn install

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/

unit_e2e_test:
  stage: test
  script: yarn test