image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/

unit_e2e_test:
  stage: test
  script: yarn test

deploy:
  stage: deploy
  script:
    - docker build . -t portfolio
    - docker run -d -p 8080:80 portfolio
  when: manual